// Hook-driven agent attention (Phase 1).
//
// Each launched Claude/Codex agent runs a tiny `notify.sh` that POSTs its
// lifecycle events to an always-on local Clauge endpoint, which sets the
// per-terminal "awaiting input" state authoritatively — so the amber dot /
// desktop badge / push stop being driven by output guessing. Zero mutation
// of the user's global agent config files: Claude hooks arrive only via the
// `--settings` file we own under `~/.clauge/`; Codex only via `-c notify`.
//
// This module owns:
//   - the generated assets (`notify.sh`, `claude-settings.json`) under
//     `~/.clauge/hooks/`, written idempotently at startup;
//   - the resolved hook endpoint base URL, stashed in a global so the spawn
//     path can read it after the always-on server binds.

use std::path::PathBuf;
use std::sync::{Mutex, OnceLock};

/// Resolved hook endpoint base URL (e.g. `http://127.0.0.1:7421/agent-hook`),
/// set when the always-on server binds. `None` until then — the spawn path
/// skips hook env/flag injection while it's unset.
static HOOK_URL: OnceLock<Mutex<Option<String>>> = OnceLock::new();

fn hook_url_cell() -> &'static Mutex<Option<String>> {
    HOOK_URL.get_or_init(|| Mutex::new(None))
}

/// Record the hook endpoint base URL. Called when the server binds.
pub fn set_hook_url(url: String) {
    *hook_url_cell().lock().unwrap() = Some(url);
}

/// Read the hook endpoint base URL, if the server has bound. `None` =
/// endpoint not available yet → spawn path skips injection.
pub fn hook_url() -> Option<String> {
    hook_url_cell().lock().unwrap().clone()
}

/// `~/.clauge/hooks` — where the generated assets live.
fn hooks_dir() -> Option<PathBuf> {
    dirs::home_dir().map(|h| h.join(".clauge").join("hooks"))
}

/// Absolute path to the generated `notify.sh`.
pub fn notify_script_path() -> Option<String> {
    hooks_dir().map(|d| d.join("notify.sh").to_string_lossy().to_string())
}

/// Absolute path to the generated Claude `--settings` file.
pub fn claude_settings_path() -> Option<String> {
    hooks_dir().map(|d| d.join("claude-settings.json").to_string_lossy().to_string())
}

/// The notify script body. Reads the event JSON from `$1` (Codex passes the
/// payload as argv) OR stdin (Claude), extracts the event name from
/// `hook_event_name` (Claude) or `type` (Codex), and POSTs a minimal JSON
/// body to `$CLAUGE_HOOK_URL`. Never blocks the agent and ALWAYS exits 0 —
/// on any parse/transport failure it stays silent rather than defaulting to
/// a state.
const NOTIFY_SH: &str = r#"#!/usr/bin/env bash
# Generated by Clauge — do not edit. Regenerated on each app start.
# Reports an agent lifecycle event to the local Clauge hook endpoint.
# Reads the event JSON from argv ($1, Codex) or stdin (Claude); extracts
# the event name from `hook_event_name` (Claude) or `type` (Codex). On any
# failure it stays silent and exits 0 so the agent is never blocked and no
# state is guessed.

set +e

payload="${1:-}"
if [ -z "$payload" ]; then
  payload="$(cat 2>/dev/null)"
fi

# Extract the event name: prefer Claude's `hook_event_name`, fall back to
# Codex's `type`. Pure-sed extraction so we don't depend on `jq`.
event="$(printf '%s' "$payload" | sed -n 's/.*"hook_event_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n1)"
if [ -z "$event" ]; then
  event="$(printf '%s' "$payload" | sed -n 's/.*"type"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n1)"
fi

if [ -z "$event" ]; then
  exit 0
fi
if [ -z "$CLAUGE_HOOK_URL" ] || [ -z "$CLAUGE_TERMINAL_ID" ]; then
  exit 0
fi

# Escape backslashes and double quotes so the values can't break the JSON.
esc() { printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'; }
tid="$(esc "$CLAUGE_TERMINAL_ID")"
evt="$(esc "$event")"
ref="$(esc "${CLAUGE_SESSION_REF:-}")"

body="{\"terminalId\":\"$tid\",\"eventType\":\"$evt\",\"sessionRef\":\"$ref\"}"

curl -sX POST "$CLAUGE_HOOK_URL" \
  -H 'content-type: application/json' \
  -d "$body" \
  --connect-timeout 2 --max-time 5 >/dev/null 2>&1 || true

exit 0
"#;

/// Build the Claude `--settings` JSON: a minimal file containing ONLY a
/// `hooks` block that runs `notify.sh` for the lifecycle events we care
/// about. `Notification` + `PreToolUse` (matcher `*`) signal needs-user;
/// `Stop` / `SessionStart` / `SessionEnd` clear. Auth / MCP live in the
/// user's own settings.json and are unaffected by this additional source.
fn claude_settings_json(notify_path: &str) -> String {
    let cmd = serde_json::Value::String(notify_path.to_string());
    let entry = serde_json::json!({
        "type": "command",
        "command": cmd,
    });
    let hooks_only = serde_json::json!([{ "hooks": [entry] }]);
    let hooks_matched = serde_json::json!([{ "matcher": "*", "hooks": [entry] }]);
    let settings = serde_json::json!({
        "hooks": {
            "Notification": hooks_only,
            "PreToolUse": hooks_matched,
            "Stop": hooks_only,
            "SessionStart": hooks_only,
            "SessionEnd": hooks_only,
        }
    });
    serde_json::to_string_pretty(&settings).unwrap_or_else(|_| "{}".to_string())
}

/// Write the hook assets (`notify.sh`, `claude-settings.json`) to
/// `~/.clauge/hooks/` idempotently. Best-effort: callers log + continue on
/// failure. Always rewrites so an upgraded Clauge refreshes the templates.
pub fn ensure_hook_assets() -> std::io::Result<()> {
    let dir = hooks_dir()
        .ok_or_else(|| std::io::Error::new(std::io::ErrorKind::NotFound, "no home dir"))?;
    std::fs::create_dir_all(&dir)?;

    let notify = dir.join("notify.sh");
    std::fs::write(&notify, NOTIFY_SH)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&notify, std::fs::Permissions::from_mode(0o755))?;
    }

    let notify_abs = notify.to_string_lossy().to_string();
    let settings = dir.join("claude-settings.json");
    std::fs::write(&settings, claude_settings_json(&notify_abs))?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn claude_settings_registers_expected_events() {
        let json = claude_settings_json("/home/u/.clauge/hooks/notify.sh");
        let v: serde_json::Value = serde_json::from_str(&json).unwrap();
        let hooks = &v["hooks"];
        for ev in ["Notification", "PreToolUse", "Stop", "SessionStart", "SessionEnd"] {
            assert!(hooks.get(ev).is_some(), "missing event {ev}");
        }
        // PreToolUse carries the wildcard matcher.
        assert_eq!(hooks["PreToolUse"][0]["matcher"], "*");
        // The command resolves to the absolute notify.sh path.
        assert_eq!(
            hooks["Notification"][0]["hooks"][0]["command"],
            "/home/u/.clauge/hooks/notify.sh"
        );
    }
}
