// Hook-driven agent attention (Phase 1).
//
// Each launched Claude/Codex agent runs a tiny `notify.sh` that POSTs its
// lifecycle events to an always-on local ZeroAny Workbench endpoint, which sets the
// per-terminal "awaiting input" state authoritatively — so the amber dot /
// desktop badge / push stop being driven by output guessing. Zero mutation
// of the user's global agent config files: Claude hooks arrive only via the
// `--settings` file we own under `~/.zeroany-workbench/`; Codex only via `-c notify`.
//
// This module owns:
//   - the generated assets (`notify.sh`, `claude-settings.json`) under
//     `~/.zeroany-workbench/hooks/`, written idempotently at startup;
//   - the resolved hook endpoint base URL, stashed in a global so the spawn
//     path can read it after the always-on server binds.

use std::collections::HashMap;
use std::io::{BufRead, BufReader};
use std::path::PathBuf;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex, OnceLock};
use std::time::{Duration, Instant};

/// Resolved hook endpoint base URL (e.g. `http://127.0.0.1:7421/agent-hook`),
/// set when the always-on server binds. `None` until then — the spawn path
/// skips hook env/flag injection while it's unset.
static HOOK_URL: OnceLock<Mutex<Option<String>>> = OnceLock::new();

fn hook_url_cell() -> &'static Mutex<Option<String>> {
    HOOK_URL.get_or_init(|| Mutex::new(None))
}

/// Record the hook endpoint base URL. Called when the server binds.
pub fn set_hook_url(url: String) {
    *hook_url_cell().lock().unwrap() = Some(url);
}

/// Read the hook endpoint base URL, if the server has bound. `None` =
/// endpoint not available yet → spawn path skips injection.
pub fn hook_url() -> Option<String> {
    hook_url_cell().lock().unwrap().clone()
}

/// `~/.zeroany-workbench/hooks` — where the generated assets live.
fn hooks_dir() -> Option<PathBuf> {
    dirs::home_dir().map(|h| h.join(".zeroany-workbench").join("hooks"))
}

/// `~/.zeroany-workbench/opencode` — a ZeroAny Workbench-owned, scoped OpenCode config dir passed to
/// the agent via `OPENCODE_CONFIG_DIR`. OpenCode *merges* this with the user's
/// real config (`~/.config/opencode`), so our notify plugin loads without ever
/// touching the user's config or auth. We never write anything but the plugin.
fn opencode_config_dir() -> Option<PathBuf> {
    dirs::home_dir().map(|h| h.join(".zeroany-workbench").join("opencode"))
}

/// Absolute path to the ZeroAny Workbench-scoped `OPENCODE_CONFIG_DIR`, for the spawn path.
pub fn opencode_config_dir_path() -> Option<String> {
    opencode_config_dir().map(|d| d.to_string_lossy().to_string())
}

/// Absolute path to the generated `notify.sh`. `None` if the asset isn't
/// on disk (generation failed/skipped) so the spawn path injects a hook
/// only when there's a real script to point at.
pub fn notify_script_path() -> Option<String> {
    let p = hooks_dir()?.join("notify.sh");
    p.exists().then(|| p.to_string_lossy().to_string())
}

/// Absolute path to the generated Claude `--settings` file. `None` if the
/// asset isn't on disk (see `notify_script_path`).
pub fn claude_settings_path() -> Option<String> {
    let p = hooks_dir()?.join("claude-settings.json");
    p.exists().then(|| p.to_string_lossy().to_string())
}

/// The notify script body. Reads the event JSON from `$1` (Codex passes the
/// payload as argv) OR stdin (Claude), extracts the event name from
/// `hook_event_name` (Claude) or `type` (Codex), and POSTs a minimal JSON
/// body to `$ZEROANY_WORKBENCH_HOOK_URL`. Never blocks the agent and ALWAYS exits 0 —
/// on any parse/transport failure it stays silent rather than defaulting to
/// a state.
const NOTIFY_SH: &str = r#"#!/usr/bin/env bash
# Generated by ZeroAny Workbench — do not edit. Regenerated on each app start.
# Reports an agent lifecycle event to the local ZeroAny Workbench hook endpoint.
# Reads the event JSON from argv ($1, Codex) or stdin (Claude); extracts
# the event name from `hook_event_name` (Claude) or `type` (Codex). On any
# failure it stays silent and exits 0 so the agent is never blocked and no
# state is guessed.

set +e

payload="${1:-}"
if [ -z "$payload" ]; then
  payload="$(cat 2>/dev/null)"
fi

# Extract the event name: prefer Claude's `hook_event_name`, fall back to
# Codex's `type`. Pure-sed extraction so we don't depend on `jq`.
event="$(printf '%s' "$payload" | sed -n 's/.*"hook_event_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n1)"
if [ -z "$event" ]; then
  event="$(printf '%s' "$payload" | sed -n 's/.*"type"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n1)"
fi

if [ -z "$event" ]; then
  exit 0
fi
if [ -z "$ZEROANY_WORKBENCH_HOOK_URL" ] || [ -z "$ZEROANY_WORKBENCH_TERMINAL_ID" ]; then
  exit 0
fi

# Escape backslashes and double quotes so the values can't break the JSON.
esc() { printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'; }
tid="$(esc "$ZEROANY_WORKBENCH_TERMINAL_ID")"
evt="$(esc "$event")"
ref="$(esc "${ZEROANY_WORKBENCH_SESSION_REF:-}")"

body="{\"terminalId\":\"$tid\",\"eventType\":\"$evt\",\"sessionRef\":\"$ref\"}"

curl -sX POST "$ZEROANY_WORKBENCH_HOOK_URL" \
  -H 'content-type: application/json' \
  -d "$body" \
  --connect-timeout 2 --max-time 5 >/dev/null 2>&1 || true

exit 0
"#;

/// OpenCode notify plugin (Phase 2). Ported from superset's plugin, but POSTs
/// lifecycle events DIRECTLY to `$ZEROANY_WORKBENCH_HOOK_URL` via `fetch` instead of
/// shelling out to notify.sh. Loaded only via our scoped `OPENCODE_CONFIG_DIR`,
/// so the user's `~/.config/opencode` and auth are untouched.
///
/// Robustness (mirrors superset): root-session-scoped (subagent/child sessions
/// — those with a `parentID` — never drive state), idle→busy / busy→idle dedup
/// so it can't spam, and a total no-op when `ZEROANY_WORKBENCH_HOOK_URL` /
/// `ZEROANY_WORKBENCH_TERMINAL_ID` are unset. Every POST is wrapped in try/catch so a hook
/// failure can never break the agent.
const OPENCODE_PLUGIN_JS: &str = r#"// Generated by ZeroAny Workbench — do not edit. Regenerated on each app start.
// OpenCode notify plugin: POSTs root-session lifecycle events to the local
// ZeroAny Workbench hook endpoint so attention state is authoritative (not output-guessed).
export const ZeroAnyWorkbenchNotifyPlugin = async ({ client }) => {
  if (globalThis.__zeroanyWorkbenchOpencodeNotifyPlugin) return {};
  globalThis.__zeroanyWorkbenchOpencodeNotifyPlugin = true;

  const hookUrl = process?.env?.ZEROANY_WORKBENCH_HOOK_URL;
  const terminalId = process?.env?.ZEROANY_WORKBENCH_TERMINAL_ID;
  // No ZeroAny Workbench context → silent no-op (never touches a non-ZeroAny Workbench OpenCode).
  if (!hookUrl || !terminalId) return {};

  const sessionRef = process?.env?.ZEROANY_WORKBENCH_SESSION_REF || "";
  const debug = process?.env?.ZEROANY_WORKBENCH_DEBUG === "1";
  const log = (...a) => { if (debug) console.log("[zeroany-workbench-opencode]", ...a); };

  // Dedup + root-session scoping state.
  let currentState = "idle"; // 'idle' | 'busy'
  let rootSessionID = null;
  let stopSent = false;
  const childSessionCache = new Map();

  // Best-effort POST. Any failure is swallowed so the agent never breaks.
  const notify = async (eventType) => {
    log("notify", eventType);
    try {
      await fetch(hookUrl, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ terminalId, eventType, sessionRef }),
      });
    } catch (err) {
      log("notify failed", err?.message || err);
    }
  };

  // A session is a child/subagent if it has a parentID. On lookup failure we
  // assume child (true) to avoid false-positive state changes from subagents.
  const isChildSession = async (sessionID) => {
    if (!sessionID) return true;
    if (childSessionCache.has(sessionID)) return childSessionCache.get(sessionID);
    let child = true;
    try {
      const list = await client?.session?.list?.();
      const sessions = Array.isArray(list) ? list : (list?.data ?? []);
      const found = sessions.find((s) => (s?.id ?? s?.info?.id) === sessionID);
      const info = found?.info ?? found;
      if (info) child = Boolean(info.parentID);
    } catch (err) {
      log("isChildSession lookup failed", err?.message || err);
    }
    childSessionCache.set(sessionID, child);
    return child;
  };

  const handleBusy = async (sessionID) => {
    if (!rootSessionID) rootSessionID = sessionID;
    if (sessionID !== rootSessionID) return;
    if (currentState === "idle") {
      currentState = "busy";
      stopSent = false;
      await notify("Start");
    }
  };

  const handleStop = async (sessionID) => {
    if (rootSessionID && sessionID !== rootSessionID) return;
    if (currentState === "busy" && !stopSent) {
      currentState = "idle";
      stopSent = true;
      await notify("Stop");
      rootSessionID = null;
    }
  };

  return {
    "permission.ask": async (input) => {
      const sessionID =
        input?.sessionID ?? input?.properties?.sessionID ?? input?.session?.id ?? null;
      if (sessionID && (await isChildSession(sessionID))) return;
      await notify("PermissionRequest");
    },
    event: async ({ event }) => {
      const type = event?.type;
      const props = event?.properties ?? {};
      const sessionID = props.sessionID ?? props.info?.id ?? null;
      log("event", type, sessionID);

      if (type === "session.created") {
        const isChild = Boolean(props.info?.parentID);
        if (sessionID) childSessionCache.set(sessionID, isChild);
        if (!isChild) await notify("SessionStart");
        return;
      }
      if (type === "session.deleted") {
        const cached = sessionID != null ? childSessionCache.get(sessionID) : undefined;
        const isChild = cached !== undefined ? cached : await isChildSession(sessionID);
        if (!isChild) await notify("SessionEnd");
        return;
      }

      if (type === "session.status") {
        const status = props.status ?? props.info?.status;
        if (sessionID && (await isChildSession(sessionID))) return;
        if (status === "busy") await handleBusy(sessionID);
        else if (status === "idle") await handleStop(sessionID);
        return;
      }
      // Legacy event names from older OpenCode builds.
      if (type === "session.busy") {
        if (sessionID && (await isChildSession(sessionID))) return;
        await handleBusy(sessionID);
        return;
      }
      if (type === "session.idle" || type === "session.error") {
        if (sessionID && (await isChildSession(sessionID))) return;
        await handleStop(sessionID);
      }
    },
  };
};
"#;

/// Build the Claude `--settings` JSON: a minimal file containing ONLY a
/// `hooks` block that runs `notify.sh` for the lifecycle events we care
/// about. `Notification` + `PreToolUse` (matcher `*`) signal needs-user;
/// `PostToolUse` / `Stop` / `UserPromptSubmit` / `SessionStart` /
/// `SessionEnd` clear. `PostToolUse` is essential: `PreToolUse` fires for
/// every tool (not just gated ones), so without the matching clear an
/// auto-approved tool would leave a stale "needs you" flag until `Stop`.
/// Auth / MCP live in the user's own settings.json and are unaffected by
/// this additional source.
fn claude_settings_json(notify_path: &str) -> String {
    let cmd = serde_json::Value::String(notify_path.to_string());
    let entry = serde_json::json!({
        "type": "command",
        "command": cmd,
    });
    let hooks_only = serde_json::json!([{ "hooks": [entry] }]);
    let hooks_matched = serde_json::json!([{ "matcher": "*", "hooks": [entry] }]);
    let settings = serde_json::json!({
        "hooks": {
            "Notification": hooks_only,
            "PreToolUse": hooks_matched,
            "PostToolUse": hooks_matched,
            "Stop": hooks_only,
            "UserPromptSubmit": hooks_only,
            "SessionStart": hooks_only,
            "SessionEnd": hooks_only,
        }
    });
    serde_json::to_string_pretty(&settings).unwrap_or_else(|_| "{}".to_string())
}

/// Write the hook assets (`notify.sh`, `claude-settings.json`) to
/// `~/.zeroany-workbench/hooks/` idempotently. Best-effort: callers log + continue on
/// failure. Always rewrites so an upgraded ZeroAny Workbench refreshes the templates.
pub fn ensure_hook_assets() -> std::io::Result<()> {
    let dir = hooks_dir()
        .ok_or_else(|| std::io::Error::new(std::io::ErrorKind::NotFound, "no home dir"))?;
    std::fs::create_dir_all(&dir)?;

    let notify = dir.join("notify.sh");
    std::fs::write(&notify, NOTIFY_SH)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&notify, std::fs::Permissions::from_mode(0o755))?;
    }

    let notify_abs = notify.to_string_lossy().to_string();
    let settings = dir.join("claude-settings.json");
    std::fs::write(&settings, claude_settings_json(&notify_abs))?;

    // OpenCode notify plugin (Phase 2), under the ZeroAny Workbench-scoped config dir
    // we pass via OPENCODE_CONFIG_DIR. `<config-dir>/plugin/*.js` is the dir
    // OpenCode auto-loads plugins from; we own only this file.
    if let Some(oc_dir) = opencode_config_dir() {
        let plugin_dir = oc_dir.join("plugin");
        std::fs::create_dir_all(&plugin_dir)?;
        std::fs::write(plugin_dir.join("notify.js"), OPENCODE_PLUGIN_JS)?;
    }

    Ok(())
}

// ----------------------------------------------------------------------------
// Codex permission/start watcher (Phase 2).
//
// Codex's native `-c notify` callback (Phase 1) only reports completion. For
// permission prompts and turn starts we tail Codex's per-spawn TUI session log
// (`CODEX_TUI_SESSION_LOG_PATH`, a unique temp file per terminal) and map two
// line markers onto `set_hook_event`. We use a per-spawn log rather than the
// global rollout dir so concurrent Codex sessions never cross signals, and the
// file is deleted on stop so nothing leaks.
// ----------------------------------------------------------------------------

/// Registry of running codex watchers keyed by terminal_id → stop flag. The
/// watcher thread polls the flag and exits when it flips; `stop_codex_watcher`
/// sets it and deletes the temp log.
fn codex_watchers() -> &'static Mutex<HashMap<String, Arc<AtomicBool>>> {
    static WATCHERS: OnceLock<Mutex<HashMap<String, Arc<AtomicBool>>>> = OnceLock::new();
    WATCHERS.get_or_init(|| Mutex::new(HashMap::new()))
}

/// Per-spawn temp path for a codex TUI session log, e.g.
/// `<tmp>/zeroany-workbench-codex-<terminal_id>.jsonl`. Used both for the spawn env and
/// by the watcher.
pub fn codex_session_log_path(terminal_id: &str) -> PathBuf {
    std::env::temp_dir().join(format!("zeroany-workbench-codex-{terminal_id}.jsonl"))
}

/// How long the watcher waits for the log file to first appear before giving
/// up (backstop against a codex that never records a session).
const CODEX_LOG_APPEAR_TIMEOUT: Duration = Duration::from_secs(60);

/// Start a background watcher that tails `log_path` and forwards codex
/// permission/start events to `set_hook_event`. Idempotent per terminal: a
/// second call for the same id replaces the prior watcher's stop flag. The
/// watcher self-exits if the log never appears within `CODEX_LOG_APPEAR_TIMEOUT`
/// or once the stop flag flips. Best-effort: never panics on IO errors.
pub fn start_codex_log_watcher(terminal_id: String, log_path: PathBuf) {
    let stop = Arc::new(AtomicBool::new(false));
    codex_watchers()
        .lock()
        .unwrap()
        .insert(terminal_id.clone(), stop.clone());

    std::thread::spawn(move || {
        let started = Instant::now();

        // Wait for the file to appear (codex creates it on first record).
        loop {
            if stop.load(Ordering::Relaxed) {
                return;
            }
            if log_path.exists() {
                break;
            }
            if started.elapsed() >= CODEX_LOG_APPEAR_TIMEOUT {
                log::debug!(
                    target: "agent::hooks",
                    "codex watcher giving up: log never appeared for {terminal_id}"
                );
                codex_watchers().lock().unwrap().remove(&terminal_id);
                return;
            }
            std::thread::sleep(Duration::from_millis(200));
        }

        let file = match std::fs::File::open(&log_path) {
            Ok(f) => f,
            Err(e) => {
                log::debug!(target: "agent::hooks", "codex watcher open failed for {terminal_id}: {e}");
                codex_watchers().lock().unwrap().remove(&terminal_id);
                return;
            }
        };
        let mut reader = BufReader::new(file);

        // `tail -F` semantics: read available lines; on EOF sleep and retry,
        // re-checking the stop flag each loop so teardown is prompt.
        loop {
            if stop.load(Ordering::Relaxed) {
                break;
            }
            let mut line = String::new();
            match reader.read_line(&mut line) {
                Ok(0) => {
                    std::thread::sleep(Duration::from_millis(200));
                }
                Ok(_) => {
                    // Permission request outranks start; check it first.
                    if line.contains("_approval_request\"") {
                        crate::companion::fanout::set_hook_event(&terminal_id, "PermissionRequest");
                    } else if line.contains("\"UserTurn\"")
                        && line.contains("\"dir\":\"from_tui\"")
                        && line.contains("\"kind\":\"op\"")
                    {
                        crate::companion::fanout::set_hook_event(&terminal_id, "Start");
                    }
                }
                Err(_) => {
                    // Transient IO error — pause and retry rather than die.
                    std::thread::sleep(Duration::from_millis(200));
                }
            }
        }
    });
}

/// Stop a codex watcher: flip its stop flag and remove its temp log. Safe to
/// call for an unknown / already-stopped terminal (no-op). Best-effort cleanup.
pub fn stop_codex_watcher(terminal_id: &str) {
    let flag = codex_watchers().lock().unwrap().remove(terminal_id);
    if let Some(flag) = flag {
        flag.store(true, Ordering::Relaxed);
    }
    let _ = std::fs::remove_file(codex_session_log_path(terminal_id));
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn claude_settings_registers_expected_events() {
        let json = claude_settings_json("/home/u/.zeroany-workbench/hooks/notify.sh");
        let v: serde_json::Value = serde_json::from_str(&json).unwrap();
        let hooks = &v["hooks"];
        for ev in [
            "Notification",
            "PreToolUse",
            "PostToolUse",
            "Stop",
            "UserPromptSubmit",
            "SessionStart",
            "SessionEnd",
        ] {
            assert!(hooks.get(ev).is_some(), "missing event {ev}");
        }
        // PreToolUse / PostToolUse carry the wildcard matcher.
        assert_eq!(hooks["PreToolUse"][0]["matcher"], "*");
        assert_eq!(hooks["PostToolUse"][0]["matcher"], "*");
        // The command resolves to the absolute notify.sh path.
        assert_eq!(
            hooks["Notification"][0]["hooks"][0]["command"],
            "/home/u/.zeroany-workbench/hooks/notify.sh"
        );
    }
}
